extend = [
	# Build debug and release build [build|release]
	{ path = "pai-make-targets/build.toml" },

	# Fix formatting and clippy [fix|fixfmt|fixclippy|update|clippy]
	{ path = "pai-make-targets/fix.toml" },

	# Publish new crate on crates.io [publish|publishdry]
	{ path = "pai-make-targets/publish.toml" },

	# Test [test]
	{ path = "pai-make-targets/test.toml" },

	# Create a new release
	{ path = "pai-make-targets/createrelease.toml" },
]

[tasks.publishrelease]
condition = { env_set = ["OUTNAME", "ZIPOUT"], fail_message = "publishrelease: necessary env not specified" }
dependencies = [
	{ name = "update" },
	{ name = "publish" },
	{ name = "createzips" },
]
command = "gh"
args = [ "release", "create", "--prerelease", "--generate-notes", "--draft", "v${CARGO_MAKE_CRATE_VERSION}", "${ZIPOUT}/${OUTNAME}/zips/${CARGO_MAKE_CRATE_VERSION}/*.zip" ]
